document.addEventListener("DOMContentLoaded", function () {
    const compareBtn = document.getElementById('compare-btn');
    const currentLevelSelect = document.getElementById('current-level');
    const desiredLevelSelect = document.getElementById('desired-level');
    const resultsDiv = document.getElementById('comparison-results');

    // Load JSON updated
    let jsonData = [
        {
            "ID": "IA.L1-3.5.2",
            "Control": "Authentication",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "X",
            "CMMC 2": "N/A",
            "Comments": "Covered under both DISP and CMMC. DISP briefly on its industry tip:\nrecommends multifactor authentication / dual authentication. Depending on which cyber security standard is used, both essential 8and ISO 27002 discusses this in detail",
            "Control /Action": "Authenticate (or verify) the identities of those users, processes, or devices, as a prerequisite to allowing access to organizational information systems."
        },
        {
            "ID": "PE.L1-3.10.5",
            "Control": "Manage Physical Access",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "X",
            "CMMC 2": "N/A",
            "Comments": "Covered under both DISP and CMMC.",
            "Control /Action": "Control and manage physical access devices."
        },
        {
            "ID": "PE.L1-3.10.3",
            "Control": "Escort Visitors",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "X",
            "CMMC 2": "N/A",
            "Comments": "Covered under both DISP and CMMC.",
            "Control /Action": "Escort visitors and monitor visitor activity."
        },
        {
            "ID": "IA.L1-3.5.1",
            "Control": "Identification",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "X",
            "CMMC 2": "N/A",
            "Comments": "Covered under both DISP and CMMC.",
            "Control /Action": "Identify information system users, processes acting on behalf of users, or devices."
        },
        {
            "ID": "SI.L1-3.14.1",
            "Control": "Flaw\nRemediation",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "X",
            "CMMC 2": "N/A",
            "Comments": "Covered under both DISP and CMMC.",
            "Control /Action": "Identify, report, and correct information and information system flaws in a timely manner."
        },
        {
            "ID": "SC.L1-3.13.5",
            "Control": "Public-Access System\nSeparation",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "X",
            "CMMC 2": "N/A",
            "Comments": "Covered under both DISP and CMMC. DISP covers this under ICT and Cyber\nassessment of systems and networks discussed further under ISO 27002\n13.1.3 Segregation in networks",
            "Control /Action": "Implement subnetworks for publicly accessible system components that are physically or logically separated from internal networks."
        },
        {
            "ID": "AC.L1- 3.1.1",
            "Control": "Authorized Access Control",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "X",
            "CMMC 2": "N/A",
            "Comments": "Covered under both DISP and CMMC. DISP mentions access control in terms of physical perimeter zones classification from zone 1 to zone 5 depending on employee clearance level for access. Also covered under ICT and Cyber depending on chosen standard and on governance for ongoing personnel security, although mentioned briefly.",
            "Control /Action": "Limit information system access to authorized users, processes acting on behalf of authorized users, or devices (including other information systems)."
        },
        {
            "ID": "AC.L1- 3.1.2",
            "Control": "Transaction & Function Control",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "X",
            "CMMC 2": "N/A",
            "Comments": "Covered under both DISP and CMMC.",
            "Control /Action": "Limit information system access to the types of transactions and functions that authorized users are permitted to execute."
        },
        {
            "ID": "PE.L1-3.10.1",
            "Control": "Limit Physical Access",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "X",
            "CMMC 2": "N/A",
            "Comments": "Covered under both DISP and CMMC. DISP more thoroughly in the physical security section breaking it down on security clearance levels and zones that can be accessed.",
            "Control /Action": "Limit physical access to organizational information systems, equipment, and the respective operating environments to authorized individuals."
        },
        {
            "ID": "PE.L1-3.10.4",
            "Control": "Physical Access Logs",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "X",
            "CMMC 2": "N/A",
            "Comments": "Covered under both DISP and CMMC.",
            "Control /Action": "Maintain audit logs of physical access."
        },
        {
            "ID": "SC.L1-3.13.1",
            "Control": "Boundary Protection",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "X",
            "CMMC 2": "N/A",
            "Comments": "Covered under both DISP and CMMC. DISP mentions briefly mentions this under personnel clearance ICT and Cyber then discusses it further under solutions in cases of security incidents giving examples of case studies.",
            "Control /Action": "Monitor, control, and protect organizational communications (i.e., information transmitted or received by organizational information systems) at the external boundaries and key internal boundaries of the information systems."
        },
        {
            "ID": "SI.L1-3.14.5",
            "Control": "System & File Scanning",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "X",
            "CMMC 2": "N/A",
            "Comments": "DISP requires assessment of network and systems under ICT and cyber, this is\ncovered more comprehensively in ISO 27002 12.2.1 Controls against malware",
            "Control /Action": "Perform periodic scans of the information system and real-time scans of files from external sources as files are downloaded, opened, or executed."
        },
        {
            "ID": "SI.L1-3.14.2",
            "Control": "Malicious Code Protection",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "X",
            "CMMC 2": "N/A",
            "Comments": "Covered under both DISP and CMMC. DISP briefly mentions this on a case study and covers using essential 8 standard application control or ISO 27002 12.2 Protection from malware",
            "Control /Action": "Provide protection from malicious code at appropriate locations within organizational information systems."
        },
        {
            "ID": "SI.L1-3.14.4",
            "Control": "Update Malicious Code Protection",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "X",
            "CMMC 2": "N/A",
            "Comments": "Covered under both DISP and CMMC. DISP covers under ICT and Cyber DISP briefly mentions this on a case study and covers using essential 8 standard application control or ISO 27002 12.2 Protection from malware",
            "Control /Action": "Update malicious code protection mechanisms when new releases are available."
        },
        {
            "ID": "AC.L1-3.1.20",
            "Control": "External Connections",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "X",
            "CMMC 2": "N/A",
            "Comments": "Covered under both DISP and CMMC.",
            "Control /Action": "Verify and control/limit connections to and use of external information systems."
        },
        {
            "ID": "AC.L1-3.1.22",
            "Control": "Control Public Information",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "N/A",
            "DISP 1/2/3": "N/A",
            "Both": "N/A",
            "Only in CMMC\nFramework": "X",
            "CMMC 1": "X",
            "CMMC 2": "N/A",
            "Comments": "No mention in DISP",
            "Control /Action": "Control information posted or processed on publicly accessible information systems."
        },
        {
            "ID": "MP.L1-3.8.3",
            "Control": "Media Disposal",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "N/A",
            "DISP 1/2/3": "X",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "X",
            "CMMC 2": "N/A",
            "Comments": "Covered under both DISP and CMMC. DISP mentions this under physical security from level 1 onwards where facilities are accredited\nto receive, handle, store and destroy information and material, covered in detail under ISO 27002 11.2.7 Secure disposal or re-use of equipment",
            "Control /Action": "Sanitize or destroy information system media containing Federal Contract Information before disposal or release for reuse."
        },
        {
            "ID": "AU.L2-3.3.4",
            "Control": "Audit Failure Alerting",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC",
            "Control /Action": "Alert in the event of an audit logging process failure."
        },
        {
            "ID": "IA.L2-3.5.9",
            "Control": "Temporary Passwords",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC. DISP advice general use of password managers and change of admin default passwords, if ISO is used, this goes into detail and mentions use and change of temporary passwords under 9.3.1 use of secret authentication information",
            "Control /Action": "Allow temporary password use for system logons with an immediate change to a permanent password."
        },
        {
            "ID": "CM.L2-3.4.4",
            "Control": "Security Impact Analysis",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC",
            "Control /Action": "Analyze the security impact of changes prior to implementation."
        },
        {
            "ID": "CM.L2-3.4.8",
            "Control": "Application Execution Policy",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC. Covered under ICT & Cyber depending on which cyber security standard is used in this case ISO 27001/27002",
            "Control /Action": "Apply deny-by-exception (blacklisting) policy to prevent the use of unauthorized software or deny-all, permit-by-exception (whitelisting) policy to allow the execution of authorized software."
        },
        {
            "ID": "AC.L2-3.1.15",
            "Control": "Privileged Remote Access",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC",
            "Control /Action": "Authorize remote execution of privileged commands and remote access to security-relevant information."
        },
        {
            "ID": "AC.L2-3.1.16",
            "Control": "Wireless Access Authorization",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "This is not mentioned in DISP but covered under ISO 27002 13.1.3 Segregation in networks Some items of access control are covered under governance and others under ICT & Cyber",
            "Control /Action": "Authorize wireless access prior to allowing such connections."
        },
        {
            "ID": "MA.L2-3.7.4",
            "Control": "Media Inspection",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC",
            "Control /Action": "Check media containing diagnostic and test programs for malicious code before the media are used in organizational systems."
        },
        {
            "ID": "MP.L2-3.8.5",
            "Control": "Media\nAccountability",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC, DISP covers in ICT and Cyber using ISO 27002 ,8.3 Media handling. ",
            "Control /Action": "Control access to media containing CUI and maintain accountability for media during transport outside of controlled areas."
        },
        {
            "ID": "CM.L2-3.4.9",
            "Control": "User-Installed Software",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC Covered under ICT & Cyber depending on which cyber security standard is used in this case  ISO 27001/27002",
            "Control /Action": "Control and monitor user-installed software."
        },
        {
            "ID": "AC.L2-3.1.18",
            "Control": "Mobile Device Connection",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC",
            "Control /Action": "Control connection of mobile devices."
        },
        {
            "ID": "MP.L2-3.8.7",
            "Control": "Removable Media",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC. DISP covers depending on the chosen ICT and\nCyber standard, ISO covers under 8.3.1 Management of removable media",
            "Control /Action": "Control the use of removable media on system components."
        },
        {
            "ID": "AU.L2-3.3.5",
            "Control": "Audit Correlation",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC",
            "Control /Action": "Correlate audit record review, analysis, and reporting processes for investigation and response to indications of unlawful, unauthorized, suspicious, or unusual activity."
        },
        {
            "ID": "AU.L2-3.3.1",
            "Control": "System Auditing",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC  DISP uses DISO to audit systems and networks (checks maturity across all 4 domains)",
            "Control /Action": "Create and retain system audit logs and records to the extent needed to enable the monitoring, analysis, investigation, and reporting of unlawful or unauthorized system activity."
        },
        {
            "ID": "CM.L2-3.4.5",
            "Control": "Access Restrictions for Change",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC",
            "Control /Action": "Define, document, approve, and enforce physical and logical access restrictions associated with changes to organizational systems."
        },
        {
            "ID": "SC.L2-3.13.6",
            "Control": "Network\nCommunication by Exception",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC.   Not mentioned in DISP but briefly mentioned in ISO 27002 9.1.1 Access\ncontrol policy",
            "Control /Action": "Deny network communications traffic by default and allow network communications traffic by exception (i.e., deny all, permit by exception)."
        },
        {
            "ID": "CA.L2-3.12.2",
            "Control": "Plan of Action",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC",
            "Control /Action": "Develop and implement plans of action designed to correct deficiencies and reduce or eliminate vulnerabilities in organizational systems."
        },
        {
            "ID": "CA.L2-3.12.4",
            "Control": "System Security Plan",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC, DISP requires a current\nsecurity risk register or any other system of risk oversight and management",
            "Control /Action": "Develop, document, and periodically update system security plans that describe system boundaries, system environments of operation, how security requirements are implemented, and the relationships with or connections to other systems."
        },
        {
            "ID": "IA.L2-3.5.6",
            "Control": "Identifier Handling",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC.  This would be covered in detail under ISO 27002 if that is the chosen standard under 9.4.2 Secure log-on procedures",
            "Control /Action": "Disable identifiers after a defined period of inactivity."
        },
        {
            "ID": "SC.L2-3.13.2",
            "Control": "Security\nEngineering",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC. DISP covers this under ICT and Cyber\ndepending on standard chosen, ISO 27002 14.2.5 Secure system engineering principles",
            "Control /Action": "Employ architectural designs, software development techniques, and systems engineering principles that promote effective information security within organizational systems."
        },
        {
            "ID": "AC.L2-3.1.13",
            "Control": "Remote Access Confidentiality",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Briefly mentioned in DISP under industry tip in ICT and Cyber then more comprehensively covered in ISO 27002",
            "Control /Action": "Employ cryptographic mechanisms to protect the confidentiality of remote access sessions."
        },
        {
            "ID": "SC.L2- 3.13.11",
            "Control": "CUI Encryption",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC. DISP does not mention this, but depending on the chosen standard, ISO 27002 covers in 10.1 Cryptographic controls",
            "Control /Action": "Employ FIPS-validated cryptography when used to protect the confidentiality of CUI."
        },
        {
            "ID": "IA.L2-3.5.4",
            "Control": "Replay-Resistant Authentication",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC.  This would be covered in detail under ISO 27002 if that is the chosen standard",
            "Control /Action": "Employ replay-resistant authentication mechanisms for network access to privileged and non-privileged accounts."
        },
        {
            "ID": "CM.L2-3.4.6",
            "Control": "Least Functionality",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC Covered under ICT & Cyber depending on which cyber security standard is used in this case ISO 27002",
            "Control /Action": "Employ the principle of least functionality by configuring organizational systems to provide only essential capabilities."
        },
        {
            "ID": "AC.L2-3.1.5",
            "Control": "Least Privilege",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under ICT & Cyber depending on standard chosen, in this case ISO 27002 ",
            "Control /Action": "Employ the principle of least privilege, including for specific security functions and privileged accounts."
        },
        {
            "ID": "AC.L2-3.1.19",
            "Control": "Encrypt CUI on Mobile",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under DISP ICT & Cyber depending on standard chosen, in this case ISO 27001/2",
            "Control /Action": "Encrypt CUI on mobile devices and mobile computing platforms."
        },
        {
            "ID": "IA.L2-3.5.7",
            "Control": "Password Complexity",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC.  Only mentioned in CMMC, DISP does not explicitly cover but advice to consider individual security and choose the most appropriate authentication, this would be covered in detail under ISO 27002 if that is the chosen standard",
            "Control /Action": "Enforce a minimum password complexity and change of characters when new passwords are created."
        },
        {
            "ID": "MA.L2-3.7.3",
            "Control": "Equipment Sanitization",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC",
            "Control /Action": "Ensure equipment removed for off-site maintenance is sanitized of any CUI."
        },
        {
            "ID": "AT.L2-3.2.1",
            "Control": "Role-Based Risk Awareness",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC",
            "Control /Action": "Ensure that managers, systems administrators, and users of organizational systems are made aware of the security risks associated with their activities and of the applicable policies, standards, and procedures related to the security of those systems."
        },
        {
            "ID": "PS.L2-3.9.2",
            "Control": "Personnel Actions",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC, DISP mentions this in terms of revalidating personnel\nclearance depending on change of circumstances and discusses it further in an industry tip case scenario",
            "Control /Action": "Ensure that organizational systems containing CUI are protected during and after personnel actions such as terminations and transfers."
        },
        {
            "ID": "AT.L2-3.2.2",
            "Control": "Role-Based Training",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC",
            "Control /Action": "Ensure that personnel are trained to carry out their assigned information security-related duties and responsibilities."
        },
        {
            "ID": "AU.L2-\n3.3.2",
            "Control": "User\nAccountability",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC, DISP is brief",
            "Control /Action": "Ensure that the actions of individual system users, can be uniquely traced to those users so they can be held accountable for their actions."
        },
        {
            "ID": "IR.L2-3.6.1",
            "Control": "Incident Handling",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC, DISP discusses this at length using Industry tip scenarios",
            "Control /Action": "Establish an operational incident-handling capability for organizational systems that includes preparation, detection, analysis, containment, recovery, and user response activities."
        },
        {
            "ID": "CM.L2-3.4.2",
            "Control": "Security Configuration Enforcement",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC. DISP uses a downloadable tool to establish baseline and align it with DISO cyber maturity model. It also recommends seeking service from IT service provider.",
            "Control /Action": "Establish and enforce security configuration settings for information technology products employed in organizational systems."
        },
        {
            "ID": "CM.L2-3.4.1",
            "Control": "System Baselining",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC. DISP briefly mentions this, then allows for choice of standard to be used.",
            "Control /Action": "Establish and maintain baseline configurations and inventories of organizational systems (including hardware, software, firmware, and documentation) throughout the respective system development life cycles."
        },
        {
            "ID": "SC.L2- 3.13.10",
            "Control": "Key Management",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC. DISP does not mention this, but depending on the chosen standard, ISO 27002 covers in 10.1.2 Key management",
            "Control /Action": "Establish and manage cryptographic keys for cryptography employed in organizational systems."
        },
        {
            "ID": "SI.L2-3.14.7",
            "Control": "Identify\nUnauthorized Use",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC, DISP using case studies and incidents and provide steps to follow",
            "Control /Action": "Identify unauthorized use of organizational systems."
        },
        {
            "ID": "SC.L2-3.13.8",
            "Control": "Data in Transit",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC. DISP does not mention this, but depending on the chosen standard, ISO 27002 covers in 13.2.1 Information transfer policies and procedures",
            "Control /Action": "Implement cryptographic mechanisms to prevent unauthorized disclosure of CUI during transmission unless otherwise protected by alternative physical safeguards."
        },
        {
            "ID": "MP.L2-3.8.6",
            "Control": "Portable Storage Encryption",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC",
            "Control /Action": "Implement cryptographic mechanisms to protect the confidentiality of CUI stored on digital media during transport unless otherwise protected by alternative physical safeguards."
        },
        {
            "ID": "MP.L2-3.8.2",
            "Control": "Media Access",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC, for DISP access to information depends on level of\nclearance. Physical security is divided into zones (1 to 5) with access controls in place, the security clearance levels determine the zone and material an\nindividual has access to.",
            "Control /Action": "Limit access to CUI on system media to authorized users."
        },
        {
            "ID": "AU.L2-3.3.9",
            "Control": "Audit\nManagement",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC",
            "Control /Action": "Limit management of audit logging functionality to a subset of privileged users."
        },
        {
            "ID": "AC.L2-3.1.8",
            "Control": "Unsuccessful Logon Attempts",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under ICT & Cyber depending on standard chosen, in this case ISO 27002 ",
            "Control /Action": "Limit unsuccessful logon attempts."
        },
        {
            "ID": "MP.L2-3.8.4",
            "Control": "Media Markings",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC.  This is covered on DISP if ISO 27002 is used under 8.2.3 Handling of assets",
            "Control /Action": "Mark media with necessary CUI markings and distribution limitations."
        },
        {
            "ID": "AC.L2-3.1.12",
            "Control": "Control Remote Access",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Briefly mentioned in DISP under industry tip in ICT and Cyber, more comprehensively covered in ISO 27002",
            "Control /Action": "Monitor and control remote access sessions."
        },
        {
            "ID": "SI.L2-3.14.6",
            "Control": "Monitor\nCommunications for Attacks",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC, DISP briefly mentions on how to manage incidents and ISO mentions as well",
            "Control /Action": "Monitor organizational systems, including inbound and outbound communications traffic, to detect attacks and indicators of potential attacks."
        },
        {
            "ID": "CA.L2-3.12.3",
            "Control": "Security Control Monitoring",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC",
            "Control /Action": "Monitor security controls on an ongoing basis to ensure the continued effectiveness of the controls."
        },
        {
            "ID": "SI.L2-3.14.3",
            "Control": "Security Alerts & Advisories",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC. DISP advocates for system monitoring and provides further information on action response on case studies. This is further covered in ISO 12.4 Logging and monitoring",
            "Control /Action": "Monitor system security alerts and advisories and take action in response."
        },
        {
            "ID": "IA.L2-3.5.11",
            "Control": "Obscure Feedback",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC.  This would be covered in detail under ISO 27002 if that is the chosen standard under 9.4.3 Password management system",
            "Control /Action": "Obscure feedback of authentication information."
        },
        {
            "ID": "MA.L2-3.7.1",
            "Control": "Perform Maintenance",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC, DISP advice use of IT service provider to ensure the systems continuously meets standard.",
            "Control /Action": "Perform maintenance on organizational systems."
        },
        {
            "ID": "RA.L2-3.11.1",
            "Control": "Risk Assessments",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC",
            "Control /Action": "Periodically assess the risk to organizational operations (including mission, functions, image, or reputation), organizational assets, and individuals, resulting from the operation of organizational systems and the associated processing, storage, or transmission of CUI."
        },
        {
            "ID": "CA.L2-3.12.1",
            "Control": "Security Control Assessment",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "covered by both",
            "Control /Action": "Periodically assess the security controls in organizational systems to determine if the controls are effective in their application."
        },
        {
            "ID": "AC.L2-3.1.7",
            "Control": "Privileged Functions",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under ICT & Cyber depending on standard chosen, in this case ISO 27002 ",
            "Control /Action": "Prevent non-privileged users from executing privileged functions and capture the execution of such functions in audit logs."
        },
        {
            "ID": "SC.L2-3.13.7",
            "Control": "Split Tunnelling",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC.   Not mentioned in DISP, but it can be considered covered under ISO 6.2.2 Teleworking if ISO27002 is covered",
            "Control /Action": "Prevent remote devices from simultaneously establishing non-remote connections with organizational systems and communicating via some other connection to resources in external networks (i.e., split tunneling)."
        },
        {
            "ID": "IA.L2-3.5.5",
            "Control": "Identifier Reuse",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC.  This would be covered in detail under ISO 27002 if that is the chosen standard under 9.4.2 Secure log-on procedures",
            "Control /Action": "Prevent reuse of identifiers for a defined period."
        },
        {
            "ID": "SC.L2-3.13.4",
            "Control": "Shared Resource Control",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC. DISP covers this under ICT and Cyber\ndepending on standard chosen, ISO 27002 discusses further under 12.1.4 Separation of development, testing and operational environments",
            "Control /Action": "Prevent unauthorized and unintended information transfer via shared system resources."
        },
        {
            "ID": "IA.L2-3.5.8",
            "Control": "Password Reuse",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC.  This would be covered in detail under ISO 27002 if that is the chosen standard",
            "Control /Action": "Prohibit password reuse for a specified number of generations."
        },
        {
            "ID": "MP.L2-3.8.8",
            "Control": "Shared Media",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC. DISP covers depending on the chosen ICT and\nCyber standard, ISO 27001/2 covers ",
            "Control /Action": "Prohibit the use of portable storage devices when such devices have no identifiable owner."
        },
        {
            "ID": "PE.L2-3.10.2",
            "Control": "Monitor Facility",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC",
            "Control /Action": "Protect and monitor the physical facility and support infrastructure for organizational systems."
        },
        {
            "ID": "AU.L2-3.3.8",
            "Control": "Audit Protection",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC",
            "Control /Action": "Protect audit information and audit logging tools from unauthorized access, modification, and deletion"
        },
        {
            "ID": "SC.L2- 3.13.15",
            "Control": "Communications Authenticity",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC. DISP does not mention this, depending on standard chosen, ISO 27002 13\nCommunications security",
            "Control /Action": "Protect the authenticity of communications sessions."
        },
        {
            "ID": "MP.L2-3.8.9",
            "Control": "Protect Backups",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC.  DISP briefly mentions this and further\ndiscusses on ICT and cyber and provides a comprehensive coverage of physical security of back up data, ISO 27002 covers under 12.3.1 Information backup",
            "Control /Action": "Protect the confidentiality of backup CUI at storage locations."
        },
        {
            "ID": "SC.L2- 3.13.16",
            "Control": "Data at Rest",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC.  DISP does not explicitly mention this, under ICT and Cyber, ISO 27002 covers under 18.1.3 Protection of records",
            "Control /Action": "Protect the confidentiality of CUI at rest."
        },
        {
            "ID": "AC.L2-3.1.17",
            "Control": "Wireless Access Protection",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "This is not mentioned in DISP but covered under ISO 27002 13.1.2 Security of network services",
            "Control /Action": "Protect wireless access using authentication and encryption."
        },
        {
            "ID": "AU.L2-3.3.7",
            "Control": "Authoritative Time Source",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC.  Only indirectly implied in DISP but explicitly discussed in ISO 27002, 12.7 Information systems audit considerations",
            "Control /Action": "Provide a system capability that compares and synchronizes internal system clocks with an authoritative source to generate time stamps for audit records."
        },
        {
            "ID": "AU.L2-3.3.6",
            "Control": "Reduction & Reporting",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC",
            "Control /Action": "Provide audit record reduction and report generation to support on-demand analysis and reporting."
        },
        {
            "ID": "MA.L2-3.7.2",
            "Control": "System Maintenance Control",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC. DISP accepts self- certification at entry level and uses CIOG (defence authority for accrediting systems) for all levels above 1 This is comprehensively covered in ISO 27002 if that is the chosen ICT standard under 14.2.2 System change control procedures",
            "Control /Action": "Provide controls on the tools, techniques, mechanisms, and personnel used to conduct system maintenance."
        },
        {
            "ID": "AT.L2-3.2.3",
            "Control": "Insider Threat Awareness",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC",
            "Control /Action": "Provide security awareness training on recognizing and reporting potential indicators of insider threat."
        },
        {
            "ID": "RA.L2-3.11.3",
            "Control": "Vulnerability Remediation",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC, DISP maintains an insider threat program with clear escalation pathways",
            "Control /Action": "Remediate vulnerabilities in accordance with risk assessments."
        },
        {
            "ID": "CM.L2-3.4.7",
            "Control": "Nonessential Functionality",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC Covered under ICT & Cyber depending on which cyber security standard is used in this case ISO 27001/2 ",
            "Control /Action": "Restrict, disable, or prevent the use of nonessential programs, functions, ports, protocols, and services."
        },
        {
            "ID": "AU.L2-3.3.3",
            "Control": "Event Review",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC briefly",
            "Control /Action": "Review and update logged events."
        },
        {
            "ID": "AC.L2-3.1.14",
            "Control": "Remote Access Routing",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Briefly mentioned in DISP under ICT and Cyber on securing cloud services",
            "Control /Action": "Route remote access via managed access control points."
        },
        {
            "ID": "RA.L2-3.11.2",
            "Control": "Vulnerability Scan",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC",
            "Control /Action": "Scan for vulnerabilities in organizational systems and applications periodically and when new vulnerabilities affecting those systems and applications are identified."
        },
        {
            "ID": "PS.L2-3.9.1",
            "Control": "Screen Individuals",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC.  Both models cover screening, DISP goes into details in depth about its screening\nprocess in line with AS 4811-2006 employment screening process and maintains a DSAP list for clearance levels it also requires a description of the\nscreening process. DISP also mentions SO sponsoring clearances.",
            "Control /Action": "Screen individuals prior to authorizing access to organizational systems containing CUI."
        },
        {
            "ID": "AC.L2-3.1.4",
            "Control": "Separation of Duties",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC  Mentioned briefly on DISP, covered under ICT and Cyber depending on standard chosen. ",
            "Control /Action": "Separate the duties of individuals to reduce the risk of malevolent activity without collusion."
        },
        {
            "ID": "SC.L2-3.13.3",
            "Control": "Role Separation",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC. DISP covers this under ICT and Cyber\ndepending on standard chosen, ISO 27002 discusses further under 9.1.2 Access to networks and network services",
            "Control /Action": "Separate user functionality from system management functionality."
        },
        {
            "ID": "IA.L2-3.5.10",
            "Control": "Cryptographically Protected Passwords",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC.   This would be covered in detail under ISO 27002 if that is the chosen standard under 9.4.2 Secure log-on procedures",
            "Control /Action": "Store and transmit only cryptographically protected passwords."
        },
        {
            "ID": "MA.L2-3.7.6",
            "Control": "Maintenance Personnel",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC, DISP is covered under ISO 27002\n11.2.4 Equipment maintenance",
            "Control /Action": "Supervise the maintenance activities of maintenance personnel without required access authorization."
        },
        {
            "ID": "AC.L2-3.1.11",
            "Control": "Session Termination",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC",
            "Control /Action": "Terminate (automatically) a user session after a defined condition."
        },
        {
            "ID": "SC.L2-3.13.9",
            "Control": "Connections Termination",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC. DISP briefly covers this under ICT and Cyber and discusses further on ISO 27002 9.4.2 Secure log-on procedures",
            "Control /Action": "Terminate network connections associated with communications sessions at the end of the sessions or after a defined period of inactivity."
        },
        {
            "ID": "IR.L2-3.6.2",
            "Control": "Incident Reporting",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC, DISP requires maintain an inside thereat program with risks and mitigation strategies",
            "Control /Action": "Track, document, and report incidents to designated officials and/or authorities both internal and external to the organization"
        },
        {
            "ID": "CM.L2-3.4.3",
            "Control": "System Change Management",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC",
            "Control /Action": "Track, review, approve or disapprove, and log changes to organizational systems."
        },
        {
            "ID": "IA.L2-3.5.3",
            "Control": "Multifactor Authentication",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC",
            "Control /Action": "Use multifactor authentication for local and network access to privileged accounts and for network access to non-privileged accounts."
        },
        {
            "ID": "AC.L2-3.1.6",
            "Control": "Non-Privileged Account Use",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under ICT & Cyber depending on standard chosen, in this case ISO 27002 ",
            "Control /Action": "Use non-privileged accounts or roles when accessing nonsecurity functions."
        },
        {
            "ID": "AC.L2-3.1.10",
            "Control": "Session Lock",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC",
            "Control /Action": "Use session lock with pattern-hiding displays to prevent access and viewing of data after a period of inactivity."
        },
        {
            "ID": "SC.L2- 3.13.13",
            "Control": "Mobile Code",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "N/A",
            "DISP 1/2/3": "N/A",
            "Both": "N/A",
            "Only in CMMC\nFramework": "X",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "No mention in DISP",
            "Control /Action": "Control and monitor the use of mobile code."
        },
        {
            "ID": "SC.L2- 3.13.14",
            "Control": "Voice over\nInternet Protocol",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "N/A",
            "DISP 1/2/3": "N/A",
            "Both": "N/A",
            "Only in CMMC\nFramework": "X",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "No mention in DISP",
            "Control /Action": "Control and monitor the use of Voice over Internet Protocol (VoIP) technologies."
        },
        {
            "ID": "AC.L2- 3.1.3",
            "Control": "Control CUI Flow",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "N/A",
            "DISP 1/2/3": "N/A",
            "Both": "N/A",
            "Only in CMMC\nFramework": "X",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "No mention in DISP",
            "Control /Action": "Control the flow of CUI in accordance with approved authorizations."
        },
        {
            "ID": "PE.L2-3.10.6",
            "Control": "Alternative Work Sites",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "N/A",
            "DISP 1/2/3": "N/A",
            "Both": "N/A",
            "Only in CMMC\nFramework": "X",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "No mention in DISP",
            "Control /Action": "Enforce safeguarding measures for CUI at alternate work sites."
        },
        {
            "ID": "AC.L2-3.1.21",
            "Control": "Portable Storage Use",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "N/A",
            "DISP 1/2/3": "N/A",
            "Both": "N/A",
            "Only in CMMC\nFramework": "X",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "No mention in DISP",
            "Control /Action": "Limit use of portable storage devices on external systems."
        },
        {
            "ID": "SC.L2- 3.13.12",
            "Control": "Collaborative Device Control",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "N/A",
            "DISP 1/2/3": "N/A",
            "Both": "N/A",
            "Only in CMMC\nFramework": "X",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "No mention in DISP",
            "Control /Action": "Prohibit remote activation of collaborative computing devices and provide indication of devices in use to users present at the device."
        },
        {
            "ID": "MP.L2-3.8.1",
            "Control": "Media Protection",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "N/A",
            "DISP 1/2/3": "X",
            "Both": "X",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "Covered under both DISP and CMMC. DISP mentions this under physical security from level 1 onwards, covered in detail under ISO 27002 11.2.7 Secure\ndisposal or re-use of equipment",
            "Control /Action": "Protect (i.e., physically control and securely store) system media containing CUI, both paper and digital."
        },
        {
            "ID": "AC.L2-3.1.9",
            "Control": "Privacy & Security Notices",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "N/A",
            "DISP 1/2/3": "N/A",
            "Both": "N/A",
            "Only in CMMC\nFramework": "X",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "No mention in DISP",
            "Control /Action": "Provide privacy and security notices consistent with applicable CUI rules."
        },
        {
            "ID": "MA.L2-3.7.5",
            "Control": "Nonlocal\nMaintenance",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "N/A",
            "DISP 1/2/3": "N/A",
            "Both": "N/A",
            "Only in CMMC\nFramework": "X",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "No mention in DISP",
            "Control /Action": "Require multifactor authentication to establish nonlocal maintenance sessions via external network connections and terminate such connections when nonlocal maintenance is complete."
        },
        {
            "ID": "IR.L2-3.6.3",
            "Control": "Incident Response Testing",
            "Only in DISP\nFramework": "N/A",
            "DISP Entry": "N/A",
            "DISP 1/2/3": "N/A",
            "Both": "N/A",
            "Only in CMMC\nFramework": "X",
            "CMMC 1": "N/A",
            "CMMC 2": "X",
            "Comments": "No mention in DISP",
            "Control /Action": "Test the organizational incident response capability."
        },
        {
            "ID": "DISP_ICT_1",
            "Control": "Defence accreditation (IRAP assessor (expensive), Standalone device Defence network or device (dreams token, physical installation of DPN, DSN or TSN))",
            "Only in DISP\nFramework": "X",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "N/A",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "N/A",
            "Comments": "No mention in CMMC                          DISP requires defence accreditation of your network or standalone device (Levels 1,2,3)for entry level self accreditation with an IT service provider is allowed, CMMC does not",
            "Control /Action": "Get Defence accreditation of your network or standalone device"
        },
        {
            "ID": "DISP_Gov_1",
            "Control": "Governance (CSO/SO \u2013 Chief Security Office/ Security Officer)",
            "Only in DISP\nFramework": "X",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "N/A",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "N/A",
            "Comments": "No mention in CMMC",
            "Control /Action": "Must have a nominated (CSO) and (SO) who must be able to meet AGSVA eligibility requirements for Baseline clearance)\n"
        },
        {
            "ID": "DISP_Gov_2",
            "Control": "FOCI \u2013 Foreign Ownership,\nControl & Influence",
            "Only in DISP\nFramework": "X",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "N/A",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "N/A",
            "Comments": "No mention in CMMC",
            "Control /Action": "Report any substantial changes as soon as possible, including changes in Foreign Ownership, Control and Influence (FOCI) status"
        },
        {
            "ID": "DISP_Pers_1",
            "Control": "Clearance\nscreening (tiered levels by AGVSA)",
            "Only in DISP\nFramework": "X",
            "DISP Entry": "X",
            "DISP 1/2/3": "N/A",
            "Both": "N/A",
            "Only in CMMC\nFramework": "N/A",
            "CMMC 1": "N/A",
            "CMMC 2": "N/A",
            "Comments": "No mention in CMMC                                                        CMMC does not mention personnel clearance or the agency doing the clearance",
            "Control /Action": "Screening in tiered levels of Information access from official/sensitive, protected, secret and top secret"
        }
    ]

    compareBtn.addEventListener('click', function () {
        const currentLevel = currentLevelSelect.value;
        const desiredLevel = desiredLevelSelect.value;
    
        console.log('Current Level Selected:', currentLevel); // Debugging
        console.log('Desired Level Selected:', desiredLevel); // Debugging
    
        // Clear previous results
        resultsDiv.innerHTML = '';
    
        // Filter data based on DISP and CMMC levels
        const matches = jsonData.filter(item => {
            const isDispMatch = (currentLevel === 'DISP Entry' && item['DISP Entry'] === 'X') ||
                                (currentLevel === 'DISP 1/2/3' && item['DISP 1/2/3'] === 'X') ||
                                (item['Both'] === 'X');
    
            const isCmmcMatch = (desiredLevel === 'CMMC 1' && item['CMMC 1'] === 'X') ||
                                (desiredLevel === 'CMMC 2' && item['CMMC 2'] === 'X') ||
                                (desiredLevel === 'CMMC 3' && item['CMMC 3'] === 'X');
    
            return isDispMatch && isCmmcMatch;
        });
    
        // Display comparison results and highlight gaps
        if (matches.length > 0) {
            const comparisonTable = document.createElement('table');
            comparisonTable.innerHTML = `
                <tr>
                    <th>ID</th>
                    <th>Control</th>
                    <th>Comments</th>
                    <th>Control /Action</th>
                    <th>Gaps</th>
                </tr>
            `;
    
            matches.forEach(match => {
                let gapContent = '';
    
                // Compare DISP and CMMC values to identify gaps
                if (currentLevel === 'DISP Entry' && desiredLevel === 'CMMC 1' && !match['CMMC 1']) {
                    gapContent = 'Missing in CMMC 1';
                } else if (currentLevel === 'DISP 1/2/3' && desiredLevel === 'CMMC 2' && !match['CMMC 2']) {
                    gapContent = 'Missing in CMMC 2';
                } else if (currentLevel === 'DISP Entry' && desiredLevel === 'CMMC 3' && !match['CMMC 3']) {
                    gapContent = 'Missing in CMMC 3';
                }
    
                // Insert the match data, including gap content if applicable
                comparisonTable.innerHTML += `
                    <tr>
                        <td>${match.ID}</td>
                        <td>${match.Control}</td>
                        <td>${match.Comments}</td>
                        <td>${match["Control /Action"]}</td>
                        <td>${gapContent}</td>
                    </tr>
                `;
            });
    
            resultsDiv.appendChild(comparisonTable);
        } else {
            resultsDiv.innerHTML = 'No data found for the selected levels. Please check your selections and try again.';
        }
    });
    
});
